# Generated by Django 4.2.5 on 2023-10-18 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinvest',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 10, 18, 12, 21, 1, 923113, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 10, 18, 12, 21, 1, 922590, tzinfo=datetime.timezone.utc)),
        ),
    ]
