# Generated by Django 4.2.5 on 2023-11-08 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_stockinvest_date_operation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='coupon_quantity_per_year',
            field=models.IntegerField(default=0, verbose_name='Количество выплат по купонам в год'),
        ),
        migrations.AlterField(
            model_name='stockinvest',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 11, 8, 12, 10, 38, 338686, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 11, 8, 12, 10, 38, 338151, tzinfo=datetime.timezone.utc)),
        ),
    ]
