# Generated by Django 4.2.5 on 2023-11-08 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_bond_coupon_quantity_per_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='maturity_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата погашения'),
        ),
        migrations.AddField(
            model_name='bond',
            name='placement_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата размещения'),
        ),
        migrations.AlterField(
            model_name='stockinvest',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 11, 8, 12, 11, 7, 834050, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 11, 8, 12, 11, 7, 833570, tzinfo=datetime.timezone.utc)),
        ),
    ]
