# Generated by Django 4.2.5 on 2023-09-17 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_usertransaction_date_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='risk_level',
            field=models.CharField(max_length=32, verbose_name='Уровень риска'),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 9, 18, 8, 59, 47, 321522)),
        ),
    ]
