# Generated by Django 4.2.5 on 2023-11-14 05:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_bond_maturity_date_bond_placement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinvest',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 11, 14, 5, 22, 12, 973179, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 11, 14, 5, 22, 12, 972705, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_date', models.DateTimeField(verbose_name='Дата выплаты купона')),
                ('coupon_number', models.IntegerField(verbose_name='Номер купона')),
                ('pay_one_bond', models.FloatField(verbose_name='Выплата на одну облигацию')),
                ('coupon_start_date', models.DateTimeField(verbose_name='Начало купонного периода')),
                ('coupon_end_date', models.DateTimeField(verbose_name='Окончание купонного периода')),
                ('coupon_period', models.IntegerField(verbose_name='Купонный период в днях')),
                ('coupon_type', models.CharField(max_length=32, verbose_name='Тип купона')),
                ('figi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.bond')),
            ],
        ),
    ]
