# Generated by Django 4.2.5 on 2023-11-16 12:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_stockinvest_date_operation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='currency_nominal',
            field=models.CharField(default='rub', max_length=12, verbose_name='Валюта облигации'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='figi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='stocks.bond'),
        ),
        migrations.AlterField(
            model_name='stockinvest',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 11, 16, 12, 35, 5, 376822, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 11, 16, 12, 35, 5, 376350, tzinfo=datetime.timezone.utc)),
        ),
    ]
