# Generated by Django 4.2.5 on 2023-09-17 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_alter_bond_ticker_alter_currency_ticker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransaction',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 9, 18, 9, 22, 8, 457449)),
        ),
    ]
