# Generated by Django 4.2.5 on 2023-11-27 07:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0008_alter_stockinvest_date_operation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='stockinvest',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 11, 27, 7, 31, 54, 440618, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userbondtransaction',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 11, 27, 7, 31, 54, 447595, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usercurrencytransaction',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 11, 27, 7, 31, 54, 447595, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='useretftransaction',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 11, 27, 7, 31, 54, 447595, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usersharetransaction',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 11, 27, 7, 31, 54, 447595, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='PortfolioAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.FloatField(verbose_name='Количество актива')),
                ('bond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_assets', to='stocks.bond')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_assets', to='stocks.currency')),
                ('etf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_assets', to='stocks.etf')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.portfolio')),
                ('share', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_assets', to='stocks.share')),
            ],
        ),
    ]
