# Generated by Django 4.2.5 on 2023-09-17 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_alter_usertransaction_date_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='currency',
            field=models.CharField(max_length=12, verbose_name='Валюта актива'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(max_length=12, verbose_name='Валюта актива'),
        ),
        migrations.AlterField(
            model_name='etf',
            name='currency',
            field=models.CharField(max_length=12, verbose_name='Валюта актива'),
        ),
        migrations.AlterField(
            model_name='share',
            name='currency',
            field=models.CharField(max_length=12, verbose_name='Валюта актива'),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 9, 18, 9, 59, 11, 507006)),
        ),
    ]
