# Generated by Django 4.2.5 on 2023-09-18 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_alter_bond_currency_alter_currency_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='currency',
            field=models.TextField(max_length=12, verbose_name='Валюта актива'),
        ),
        migrations.AlterField(
            model_name='bond',
            name='exchange',
            field=models.TextField(max_length=64, verbose_name='Биржа'),
        ),
        migrations.AlterField(
            model_name='bond',
            name='figi',
            field=models.TextField(max_length=16),
        ),
        migrations.AlterField(
            model_name='bond',
            name='name',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='bond',
            name='ticker',
            field=models.TextField(max_length=16),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.TextField(max_length=12, verbose_name='Валюта актива'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='exchange',
            field=models.TextField(max_length=64, verbose_name='Биржа'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='figi',
            field=models.TextField(max_length=16),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='currency',
            name='ticker',
            field=models.TextField(max_length=16),
        ),
        migrations.AlterField(
            model_name='etf',
            name='currency',
            field=models.TextField(max_length=12, verbose_name='Валюта актива'),
        ),
        migrations.AlterField(
            model_name='etf',
            name='exchange',
            field=models.TextField(max_length=64, verbose_name='Биржа'),
        ),
        migrations.AlterField(
            model_name='etf',
            name='figi',
            field=models.TextField(max_length=16),
        ),
        migrations.AlterField(
            model_name='etf',
            name='name',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='etf',
            name='ticker',
            field=models.TextField(max_length=16),
        ),
        migrations.AlterField(
            model_name='share',
            name='country_of_risk',
            field=models.CharField(max_length=6, verbose_name='Страна акции'),
        ),
        migrations.AlterField(
            model_name='share',
            name='currency',
            field=models.TextField(max_length=12, verbose_name='Валюта актива'),
        ),
        migrations.AlterField(
            model_name='share',
            name='exchange',
            field=models.TextField(max_length=64, verbose_name='Биржа'),
        ),
        migrations.AlterField(
            model_name='share',
            name='figi',
            field=models.TextField(max_length=16),
        ),
        migrations.AlterField(
            model_name='share',
            name='name',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='share',
            name='share_type',
            field=models.CharField(max_length=32, verbose_name='Тип акции по классификации Тинькоф'),
        ),
        migrations.AlterField(
            model_name='share',
            name='ticker',
            field=models.TextField(max_length=16),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 9, 18, 10, 39, 5, 878017)),
        ),
    ]
