# Generated by Django 4.2.5 on 2023-09-18 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_alter_bond_currency_alter_bond_exchange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='figi',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='currency',
            name='figi',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='etf',
            name='figi',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='share',
            name='figi',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 9, 18, 10, 40, 19, 932497)),
        ),
    ]
