# Generated by Django 4.2.5 on 2023-09-18 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_alter_bond_ticker_alter_currency_ticker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='currency',
            field=models.CharField(max_length=12, verbose_name='Валюта актива'),
        ),
        migrations.AlterField(
            model_name='bond',
            name='exchange',
            field=models.CharField(max_length=64, verbose_name='Биржа'),
        ),
        migrations.AlterField(
            model_name='bond',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(max_length=12, verbose_name='Валюта актива'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='exchange',
            field=models.CharField(max_length=64, verbose_name='Биржа'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='etf',
            name='currency',
            field=models.CharField(max_length=12, verbose_name='Валюта актива'),
        ),
        migrations.AlterField(
            model_name='etf',
            name='exchange',
            field=models.CharField(max_length=64, verbose_name='Биржа'),
        ),
        migrations.AlterField(
            model_name='etf',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='share',
            name='currency',
            field=models.CharField(max_length=12, verbose_name='Валюта актива'),
        ),
        migrations.AlterField(
            model_name='share',
            name='exchange',
            field=models.CharField(max_length=64, verbose_name='Биржа'),
        ),
        migrations.AlterField(
            model_name='share',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 9, 18, 10, 42, 20, 720452)),
        ),
    ]
