# Generated by Django 4.2.5 on 2023-09-18 04:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_alter_usertransaction_date_operation_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userstock',
            name='portfolio',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_stock', to='stocks.portfolio'),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 9, 18, 4, 22, 58, 178171, tzinfo=datetime.timezone.utc)),
        ),
    ]
