# Generated by Django 4.2.5 on 2023-09-18 09:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        ('stocks', '0019_alter_userstock_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstock',
            name='portfolio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_stock', to='portfolio.portfolio'),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 9, 18, 9, 5, 16, 329457, tzinfo=datetime.timezone.utc)),
        ),
    ]
