# Generated by Django 4.2.5 on 2023-09-19 00:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0001_initial'),
        ('stocks', '0020_alter_userstock_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstock',
            name='portfolio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_asset', to='portfolio.portfolio'),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 9, 19, 0, 9, 29, 335255, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='StockInvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invest_sum_in_rub', models.FloatField()),
                ('invest_sum_in_usd', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_invest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
