# Generated by Django 4.2.5 on 2023-09-19 01:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0021_alter_userstock_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinvest',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 9, 19, 1, 56, 3, 497266, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 9, 19, 1, 56, 3, 496266, tzinfo=datetime.timezone.utc)),
        ),
    ]
