# Generated by Django 4.2.4 on 2023-08-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonsCrypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField()),
                ('token', models.CharField(max_length=16)),
                ('size', models.FloatField()),
                ('average_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonsInvestInRub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField()),
                ('size_in_rub', models.IntegerField()),
                ('size_in_usd', models.FloatField()),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonsTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField()),
                ('is_buy_or_sell', models.BooleanField()),
                ('token_1', models.CharField(max_length=16)),
                ('token_2', models.CharField(max_length=16)),
                ('price', models.FloatField()),
                ('lot', models.FloatField()),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
