# Generated by Django 4.2.5 on 2023-09-17 06:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonsTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_buy_or_sell', models.BooleanField()),
                ('token_1', models.CharField(max_length=16)),
                ('token_2', models.CharField(max_length=16)),
                ('price_in_rub', models.FloatField(default=0)),
                ('price_in_usd', models.FloatField(default=0)),
                ('lot', models.FloatField()),
                ('date_operation', models.DateField(default=datetime.datetime(2023, 9, 17, 16, 22, 49, 742192))),
                ('user', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonsCrypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=16)),
                ('lot', models.FloatField()),
                ('average_price_in_rub', models.FloatField(default=0)),
                ('average_price_in_usd', models.FloatField(default=0)),
                ('user', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
