# Generated by Django 4.2.5 on 2023-10-16 12:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonsTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_buy_or_sell', models.BooleanField(verbose_name='Покупка')),
                ('token_1', models.CharField(max_length=16, verbose_name='Первый токен')),
                ('token_2', models.CharField(max_length=16, verbose_name='Второй токен')),
                ('price_in_rub', models.FloatField(default=0, verbose_name='Цена в рублях')),
                ('price_in_usd', models.FloatField(default=0, verbose_name='Цена в $')),
                ('lot', models.FloatField(verbose_name='Количество')),
                ('date_operation', models.DateField(default=datetime.datetime(2023, 10, 16, 12, 35, 58, 239586, tzinfo=datetime.timezone.utc), verbose_name='Дата транзакции')),
                ('user', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonsCrypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=16, verbose_name='Токен')),
                ('lot', models.FloatField(verbose_name='Количество')),
                ('average_price_in_rub', models.FloatField(default=0, verbose_name='Средняя цена в рублях')),
                ('average_price_in_usd', models.FloatField(default=0, verbose_name='Средняя цена в $')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoPortfolioBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_type', models.CharField(choices=[('crypto', 'crypto'), ('stock', 'stock')], default='crypto', max_length=10)),
                ('sum_in_rub', models.FloatField()),
                ('sum_in_usd', models.FloatField()),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 10, 16, 12, 35, 58, 240585, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_portfolio_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoInvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invest_sum_in_rub', models.FloatField()),
                ('invest_sum_in_usd', models.FloatField()),
                ('date_operation', models.DateField(default=datetime.datetime(2023, 10, 16, 12, 35, 58, 240585, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_invest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
