# Generated by Django 4.2.5 on 2023-09-17 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personstransactions',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 9, 17, 8, 45, 18, 664655, tzinfo=datetime.timezone.utc)),
        ),
    ]
