# Generated by Django 4.2.5 on 2023-11-08 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_alter_cryptoinvest_date_operation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoinvest',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 11, 8, 11, 55, 34, 847038, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cryptoportfoliobalance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 11, 55, 34, 847497, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='personstransactions',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 11, 8, 11, 55, 34, 846533, tzinfo=datetime.timezone.utc), verbose_name='Дата транзакции'),
        ),
    ]
