# Generated by Django 4.2.5 on 2023-11-27 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0018_alter_cryptoinvest_date_operation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoinvest',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 11, 27, 7, 31, 54, 390983, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cryptoportfoliobalance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 7, 31, 54, 391697, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='personstransactions',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 11, 27, 7, 31, 54, 390494, tzinfo=datetime.timezone.utc), verbose_name='Дата транзакции'),
        ),
    ]
