# Generated by Django 4.2.5 on 2023-09-19 01:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crypto', '0024_alter_personstransactions_date_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personstransactions',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2023, 9, 19, 1, 56, 3, 493266, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='CryptoInvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invest_sum_in_rub', models.FloatField()),
                ('invest_sum_in_usd', models.FloatField()),
                ('date_operation', models.DateField(default=datetime.datetime(2023, 9, 19, 1, 56, 3, 494266, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_invest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
