# Generated by Django 4.2.5 on 2023-09-17 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonsDeposits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposits_summ', models.FloatField(null=True)),
                ('description', models.CharField(max_length=256)),
                ('is_open', models.BooleanField(default=1)),
                ('date_open', models.DateTimeField(auto_now_add=True)),
                ('percent', models.FloatField()),
                ('percent_capitalization', models.CharField(choices=[('daily', 'daily'), ('monthly', 'monthly'), ('annually', 'annually')], max_length=12)),
                ('date_change', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonDepositsTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_id', models.IntegerField()),
                ('is_add_or_take', models.BooleanField()),
                ('size', models.FloatField()),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
