# Generated by Django 4.2.4 on 2023-08-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonsDeposits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField()),
                ('description', models.CharField(max_length=256)),
                ('is_open', models.BooleanField()),
                ('date_open', models.DateTimeField(auto_now_add=True)),
                ('percent', models.FloatField()),
                ('percent_capitalization', models.FloatField(choices=[('daily', 'daily'), ('monthly', 'monthly'), ('annually', 'annually')])),
                ('date_change', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
