# Generated by Django 4.2.4 on 2023-08-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonDepositsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField()),
                ('is_add_or_take', models.BooleanField()),
                ('size', models.FloatField()),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='personsdeposits',
            name='deposits_summ',
            field=models.FloatField(null=True),
        ),
    ]
