# Generated by Django 4.2.4 on 2023-08-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0002_persondepositstransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonDepositsTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField()),
                ('deposit_id', models.IntegerField()),
                ('is_add_or_take', models.BooleanField()),
                ('size', models.FloatField()),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PersonDepositsTransaction',
        ),
        migrations.AlterField(
            model_name='personsdeposits',
            name='is_open',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='personsdeposits',
            name='percent_capitalization',
            field=models.CharField(choices=[('daily', 'daily'), ('monthly', 'monthly'), ('annually', 'annually')], max_length=12),
        ),
    ]
