# Generated by Django 4.2.4 on 2023-09-04 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deposits', '0003_persondepositstransactions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persondepositstransactions',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='personsdeposits',
            name='person_id',
        ),
        migrations.AddField(
            model_name='persondepositstransactions',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personsdeposits',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
