version: '3'

services:
  web:
    build:
      context: .
    ports:
      - '8000:8000'
    restart: always
    container_name: 'demo_app_django'
    volumes:
      - .:/code
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:
    image: postgres:14.9-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass

  redis:
    image: redis:7.0.5-alpine
    restart: always
    hostname: redis
    command: redis-server
    ports:
      - '6379:6379'

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A config worker --loglevel=info
    volumes:
      - .:/code
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    links:
      - redis
    depends_on:
      - web
      - redis
      - database

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A config flower
    volumes:
      - .:/code
    depends_on:
      - redis
    ports:
      - "5555:5555"

  scheduler:
    build:
      context: .
    hostname: scheduler
    entrypoint: celery
    command: -A config beat -l INFO
    volumes:
      - .:/code
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    links:
      - redis
    depends_on:
      - web
      - redis
      - database
